image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Davli.clojure@3.7.1

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: lein -v # runs during prebuild
    command: lein -v # echo 'start script'


#Name: Clojure
#Id: avli.clojure
#Description: Clojure nREPL support for Visual Studio Code
#Version: 0.12.0
#Publisher: Andrey Lisin
#VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=avli.clojure
#https://marketplace.visualstudio.com/_apis/public/gallery/publishers/avli/vsextensions/clojure/0.12.0/vspackage
